<?php

/**
 *  _   __ __ _____ _____ ___  ____  _____
 * | | / // // ___//_  _//   ||  __||_   _|
 * | |/ // /(__  )  / / / /| || |     | |
 * |___//_//____/  /_/ /_/ |_||_|     |_|
 * @link https://vistart.me/
 * @copyright Copyright (c) 2016 - 2017 vistart
 * @license https://vistart.me/license/
 */

namespace rhosocial\organization\tests\org;

use rhosocial\organization\rbac\permissions\SetUpOrganization;
use rhosocial\organization\tests\data\ar\org\Organization;
use rhosocial\organization\tests\data\ar\user\User;
use rhosocial\organization\tests\TestCase;
use Yii;

/**
 * Class OrganizationMemberRestrictTest
 * @package rhosocial\organization\tests\org
 * @version 1.0
 * @author vistart <i@vistart.me>
 */
class OrganizationMemberRestrictTest extends TestCase
{
    /**
     * @var User
     */
    protected $user;
    /**
     * @var Organization
     */
    protected $organization;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->user = new User(['password' => '123456']);
        $this->assertTrue($this->user->register([$this->user->createProfile(['nickname' => 'vistart'])]));

        $this->assertNotNull(Yii::$app->authManager->assign((new SetUpOrganization)->name, $this->user));

        $this->assertTrue($this->user->setUpOrganization($this->faker->name));
        $this->organization = $this->user->lastSetUpOrganization;
    }

    protected function tearDown()
    {
        Organization::deleteAll();
        User::deleteAll();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @group organization
     * @group member
     */
    public function testNormal()
    {
        $this->assertFalse($this->organization->isExcludeOtherMembers);
        $this->assertFalse($this->organization->isDisallowMemberJoinInOther);
        $this->assertFalse($this->organization->isOnlyAcceptCurrentOrgMember);
        $this->assertFalse($this->organization->isOnlyAcceptSuperiorOrgMember);
    }

    /**
     * @group organization
     * @group member
     */
    public function testModify()
    {
        $this->organization->isExcludeOtherMembers = true;
        $this->assertTrue($this->organization->save());
        $this->assertTrue($this->organization->isExcludeOtherMembers);

        $this->organization->isDisallowMemberJoinInOther = true;
        $this->assertTrue($this->organization->save());
        $this->assertTrue($this->organization->isDisallowMemberJoinInOther);

        $this->organization->isOnlyAcceptCurrentOrgMember = true;
        $this->assertTrue($this->organization->save());
        $this->assertTrue($this->organization->isOnlyAcceptCurrentOrgMember);

        $this->organization->isOnlyAcceptSuperiorOrgMember = true;
        $this->assertTrue($this->organization->save());
        $this->assertTrue($this->organization->isOnlyAcceptSuperiorOrgMember);
    }
}
