#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
/* Note: This command is ONLY used for testing */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$db = require(__DIR__ . '/tests/data/config.php');

$config = [
    'id' => 'testapp',
    'basePath' => __DIR__,
    'components' => [
        'db' => $db['databases']['mysql'],
        'authManager' => [
            'class' => 'rhosocial\user\rbac\DbManager',
        ],
    ],
];
Yii::setAlias('@rhosocial/organization', __DIR__);
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
